import sys
import random
from flask import Flask, render_template

app = Flask(__name__)

options = {
    "title": [
        "Fishermen",
        "The Cliff",
        "The Cave",
        "Dark Woods",
        "Peter's Secret",
        "The Forgotten Synagogue",
        "A Russian's Breath",
        "A Man and his Mule",
        "The Ruby Island",
        "The Boot in the Lake",
        "Patty Cakes Patty Cakes",
        "Jeremy's Final Request",
        "Forgotten Elm",
        "~FIN~",
        "Iago's Tomb",
        "The Teacher's Secret Cupboard",
        "Made in China",
        "No Central Heating",
        "A Cry in the Night",
        "A Lake Forgotten",
        "Pop Goes the Witzel",
        "The Astronomer's Paintbrush",
        "Raffles the Gentleman Murderer",
        "An Abandoned Hat",
        "The Cross and Kettle",
        "King George the ... 9th?",
        "Kräpp",
        "The Care Home",
        "A Latvian Memory",
        "Balkan Descent",
        "Shadowkleft",
        "A Bitch in Sleet",
        "A Knight in Tromsø",
        "The Shallow Daylight",
        "Where Daisies Die",
        "Secrets, Lies and Secrets"
    ],
    "place": [
        "a desolate Icelandic hamlet",
        "the Chernobyl fallout zone",
        "an under-funded homeless shelter",
        "18th century Beijing",
        "a jolly ghetto",
        "the salt flats of Arizona",
        "a confusing alternative history where Romania won the cold war",
        "feudal Japan",
        "Moscow's turgid business district",
        "an abbatoir for dogs",
        "Dorset's last independently owned Post Office",
        "the cut-throat world of cat-rehoming charities",
        "a world without racism",
        "the last town in Scotland without internet access",
        "a centre for re-offending youths",
        "Chef School",
        "the mountains of Tibet",
        "a cold, dark town of indeterminate Northern European locale",
        "the backdrop of the Tottenham Riots",
        "keeping with their ancient traditions",
        "a West African military junta",
        "the vast bat-markets of China",
        "a churchyard crypt",
        "a sinister nursery",
        "the local Job Centre, plagued with cuts,",
        "a cave-prison for stolen children",
        "the Tate's wonderful Turner exhibition",
        "a prison for dogs",
        "a prison for Norway's hardest criminals",
        "a mechanical graveyard"
    ],
    "char1": [
        ["an almost retired murder detective", "forms"],
        ["a local fireman with a tragic past", "forms"],
        ["several farmers with a dirty secret", "form"],
        ["a beautiful Alpaca", "forms"],
        ["a tired nanny", "forms"],
        ["a disgusting car mechanic", "forms"],
        ["wantonly destructive teenager", "forms"],
        ["the power-hungry local Mayor", "forms"],
        ["a jaded gardener", "forms"],
        ["a crafty butcher", "forms"],
        ["a cynical driving instructor", "forms"],
        ["an emotionally stunted Norwegian", "forms"],
        ["several kidnapped children", "form"],
        ["a number of Michael Jackson's former associates", "form"],
        ["Emperor Hirohito", "forms"],
        ["Michael Portillo and Michael Palin", "form"],
        ["an unemployed former dock worker", "forms"],
        ["a disgraced former prostitute who blurs the lines between sex and magic", "forms"],
        ["a media-savvy politician", "forms"],
        ["a quiet man with a dark past", "forms"],
        ["desperate criminal who's run out of track", "forms"],
        ["a complacent safety officer", "forms"],
        ["an obese personal trainer", "forms"],
        ["several generations of one family", "forms"],
        ["a boy and his long-lost twin sister", "forms"],
        ["the head of the Neighbourhood Watch", "forms"],
        ["Gareth Southgate", "forms"],
        ["Ed Miliband", "forms"],
        ["a woman with an insatiable appetite for batter", "forms"],
        ["a local cop of conspicuously different ethnicity", "forms"],
        ["a sassy female detective", "forms"],
        ["an amateur sleuth with a hidden past", "forms"],
        ["a former Royal Marine who can't forget what he saw as a child", "forms"],
        ["a violent Dutch footall hooligan", "forms"],
        ["an vigorous advocate for the death penalty", "forms"],
        ["a prison guard tortured by mental health issues", "forms"],
        ["a drug dealer with a heart of gold", "forms"],
        ["a fisherman who's always in the wrong place at the wrong time", "forms"]
    ],
    "relationship": [
        "an unlikely friendship",
        "a bond of trust",
        "a professional rivalry",
        "a distrustful alliance",
        "a secret society",
        "a club for amateur magicians",
        "the latest girl-band sensation",
        "Swindon's only legal dog-fighting ring",
        "a rich tapestry of lies",
        "a blood pact",
        "an art collective",
        "an increasingly desperate attempt to stay relevant",
        "a forbidden, lustful relationship",
        "a COVID-19 taskforce",
        "a secret daliance",
        "a love train",
        "a begrudgingly respectful relationship",
        "a political party taking advantage of growing populism",
        "a spy ring",
        "a morally dubious psychiatric practice",
        "an ethical pornography studio",
        "an illegal private detective outfit"
    ],
    "char2": [
        "an overwhelmed mother",
        "the local lacrosse team",
        "a sexually ambiguous teacher",
        "an alcoholic former cop",
        "the local priest",
        "a suspicious dog handler",
        "a frightening clown",
        "a former Mayor of London",
        "a disgraced midwife",
        "an Operation Yewtree detective",
        "a mysterious sous-chef",
        "an elderly paedophile",
        "the McCannes",
        "a wacky inventor",
        "an estate agent with shit for brains",
        "a disgraced for Olympian who shot his girlfriend",
        "a painter of bleak landscapes",
        "Rasputin's only known heir",
        "a group of Scottish Nationalists",
        "a demanding Golden Retriver",
        "an outdated working man's club comedian",
        "the winner of a bitter local election"
    ],
    "char2_possession": [
        "with a troubled step-son",
        "with an incontinent German Shepherd named Klaus",
        "with nothing to lose",
        "without honour",
        "with a secret sex addiction",
        "with a raft of sexually transmitted diseases",
        "with a locked shed",
        "in need of rehabilitating",
        "with a total lack of empathy",
        "whose social skills are lacking",
        "with a criminal record for animal abuse",
        "with a knee length macintosh",
        "who's constantly dogged by accusation of historic sex crimes",
        "with a penchant for public masturbation",
        "with proud Gypsy blood",
        "who stokes racial tensions"
    ],
    "mission": [
        "reunite the fragmented local Women's Institute",
        "get to the bottom of an historic sex crime",
        "detect ancient Roman coins",
        "bury an old secret",
        "find the truth in a world full of lies",
        "defeat racism for a second time",
        "travel back in time to prevent the Chernobyl disaster",
        "kill Hitler before it's too late",
        "beat the Russians to the Moon",
        "solve a cold case that the locals refuse to talk about",
        "avenge a distressing loss of innocence",
        "commit an even greater crime",
        "ensure Putin's continued Premiereship of Russia",
        "beat a local gang at their own game",
        "bring joy to the local children's cancer hospice",
        "professionalise the theft of trainers from Sports Direct",
        "wake from their dark, dark sleep",
        "appropriate culture willy-nilly",
        "enact a coup with frankly unimaginable consequences",
        "proves robots can love",
        "show that blood is thicker than water",
        "rush out a report totally absolving the government of any guilt",
        "expose capitalisms flaws"
    ],
    "shared_interest": [
        "shared distrust of authority",
        "paralysis from the waist down",
        "shared hatred of Women's professional football",
        "fear of large fish",
        "enjoyment of sexist jokes",
        "desire to see a United Ireland",
        "ceaseless enjoyment of trains",
        "mutual certainty in a shadowy global conspiracy",
        "mutual love of dangerous Japanese game shows",
        "ceaseless campaign of libel against Jeremy Hunt",
        "angry trumpet playing at 2am",
        "anger at dissenting views on the internet",
        "fear of dying alone",
        "belief in crystal skulls"
    ],
    "historic_element": [
        "an estranged mail-order bride",
        "a dog they'd long thought dead",
        "a commissioning editor from the BBC's Sunday Night Drama department",
        "a young, old or middle-aged Scandanavian detective",
        "a seemingly endless supply of Bosnian goons",
        "a children's TV presenter",
        "an unamed former host of Animal Hospital",
        "several scurrilous lies about pub landlord Toby",
        "a previously evicted campsite full of travellers",
        "a new take-away restaurant manager",
        "an unusually contagious virus",
        "Thor, God of Thunder,",
        "an unlicensed mini-cab driver",
        "a roaving gang of street urchins",
        "a holocaust denier",
        "seal clubbing enthusiast",
        "celibate monk"
    ],
    "historic_where": [
        "from Thailand",
        "from the dark depths of the ocean",
        "from behind the Iron Curtain",
        "with a point to prove",
        "with a burning sense of injustice",
        "with hooks for hands",
        "driving a brand new Toyota Prius",
        "with a vast trident held aloft",
        "with money on their mind",
        "who needs alcohol to function",
        "with a selection of rubber masks",
        "with their stomach full of chutney",
        "with hate in their eyes",
        "with amnesia",
        "with a beard",
        "with mascara running down their face",
        "with pain in their heart",
        "waving their colostomy bags",
        "dogged by rumours of sexual indescretions"
    ],
    "action": [
        "face their demons",
        "aggressively tailgate their enemies",
        "perform an humiliating psycho-sexual ritual",
        "put their past behind them in order to make it home in time for Gardener's World",
        "vote Labour in the local council elections",
        "tease a dog until it inevitably bites one of them",
        "cry until they die",
        "end it for good",
        "rush into moving in with their partner due to circumstance rather than love",
        "pay the piper",
        "pay off their student loan",
        "get over their fear of bears",
        "learn to love again",
        "live as a human in a world full of robots",
        "walk towards the light",
        "not mention the war",
        "rush into war once more",
        "learn to trust Tony Blair once more",
        "cry real, human tears",
        "face death",
        "kill again",
        "hog the middle lane"
    ],
    "para": [
        "In {place}, {char1} {forms} {relationship} with {char2} {char2_possession}. Their bid to {mission} starts when "
        "their {shared_interest} brings them unexpectedly together. But when {historic_element} "
        "{historic_where} re-appears, they each must {action}. {final}",
        "{char1}. {char2} {char2_possession}. In {place}, their {shared_interest} sees them form {relationship} "
        "in order to {mission}. But when {historic_element} {historic_where} returns, they may be forced to {action}. {final}",
        "When their {shared_interest} brings them together, {char1} and {char2} {char2_possession} "
        "form {relationship}. With a desire to {mission} as their goal, {place} will never be the same. "
        "But after {historic_element} {historic_where} returns, will *they* ever be the same? {final}"
    ],
    "final": [
        "Things will never be the same...",
        "Time is running out...",
        "And can love bloom in this desolate place?",
        "The sun will soon set...",
        "The clock is nearly at midnight..."
    ]

}


def sentenceCapitaliser(para):
    sentences = para.split(". ")
    sentences2 = [sentence[0].capitalize() + sentence[1:]
                  for sentence in sentences]
    string2 = '. '.join(sentences2)
    return string2


def pick(filler):
    opts = options[filler]
    chosen = random.randrange(0, len(opts))
    return opts[chosen]


@app.route('/')
def gen_show():
    title = pick("title")
    char1 = pick("char1")
    para = pick("para")
    desc = para.format(place=pick("place"),
                       char1=char1[0],
                       forms=char1[1],
                       relationship=pick("relationship"),
                       char2=pick("char2"),
                       char2_possession=pick("char2_possession"),
                       mission=pick("mission"),
                       shared_interest=pick("shared_interest"),
                       historic_element=pick("historic_element"),
                       historic_where=pick("historic_where"),
                       action=pick("action"),
                       final=pick("final"))
    return render_template("index.html", title=title.upper(), desc=sentenceCapitaliser(desc))


if __name__ == "__main__":
    app.run()
